WIP: Fix racy timers
endlessm/eos-metrics pull request #45
Opened 2021-11-17 19:15 UTC by GeorgesStavracas

This makes timers more "fragile" by allowing them be destroyed before the StartAggregateTimers() call is finished (in which case the D-Bus call is cancelled), and also removes the second async call (`emer_aggregate_timer_proxy_new()`).

This should be enough to at least send D-Bus calls in order.

https://phabricator.endlessm.com/T32671

2021-11-17 20:05 UTC, GeorgesStavracas commented
@wjt probably due to the slow hard drive of this computer, I did not manage to reproduce the triple-start issue with GVim nor any other app. This PR seems to be working normally in regular cases, but I'd appreciate if someone can report if it fixes the issue or not! I'll leave the WIP prefix until then.

2021-11-18 12:27 UTC, wjt commented
Can you reproduce it with this program?

https://gist.github.com/wjt/5d8aaa0aab65aa2f3ed1c85327904a89

2021-11-18 16:21 UTC, wjt requested changes
I can reproduce the same issue with that program, running against this branch.

I believe the fundamental issue is: until the first call to StartAggregateTimer() has returned, it's not possible for the client to call Stop() on it. And that call is made asynchronously, from a separate thread, to the daemon running in a separate process which may take some time to respond (maybe it's been swapped out to disk). So there is no guarantee how long it will take.

I see a few possible solutions:

1. Make starting or stopping the timer a blocking operation in the C API – I think this would make it much less pleasant to use in gnome-shell for example, where we really don't want to make a blocking D-Bus call from the main thread when an app is started or stopped!
2. Serialise calls to StartAggregateTimer within this eos-metrics library, so there is only at most 1 in flight at any given time (optimization: only one per (event_id, aggregate_key, payload))
3. Deduplicate timers in the library, so trying to start a duplicate one just adds to a refcount, and each stop() reduces that count, and only when the count falls to 0 stop the timer
4. Deduplicate in the same way but in the daemon
5. Allow multiple overlapping timers in the daemon, where they are currently rejected. For a well-behaving application this would, I think, be harmless. For a buggy app that runs multiple timers for the same keys at the same time, or multiple instances of the same app running at once, then this would mean double counting.  I think that in practice this will not happen, except for very small overlaps in this edge case of rapidly starting and stopping a timer.

So my suggestion is to take the 5th approach above, which I think is probably also the simplest to implement.

2021-11-18 16:21 UTC, wjt commented on eosmetrics/emtr-aggregate-timer.c
> +        g_warning ("Error creating aggregate timer: %s", error->message);
I think with this change if you construct a timer and then immediately destroy it:

```c
g_object_unref (emtr_event_recorder_start_aggregate_timer (emtr_event_recorder_get_default ()))
```

then the daemon will receive the StartAggregateTimer call, dutifully return an object path, and then the timer will still be running until the client process terminates.

2021-11-18 16:21 UTC, wjt commented on eosmetrics/emtr-aggregate-timer.c
> -  emer_aggregate_timer_proxy_new (connection,
I think part of the goal of not constructing a proxy is to remove this extra async operation when the only thing we do with the proxy is call a method on it, which we can do perfectly well with just the object path. I wonder whether `emer_aggregate_timer_proxy_new_sync` is actually guaranteed to not do any blocking stuff when we pass all these `DO_NOT` flags.

2021-11-18 20:21 UTC, closed without merging